import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Brier, MonaSans } from "@/fonts/fonts";
import Navbar from "@/components/navbar/navbar";
import { LoaderProvider } from "@/components/loader/loaderContext";
import LoaderWrapper from "@/components/loader/loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${MonaSans.variable} ${Brier.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <LoaderProvider>
            <LoaderWrapper src="/loader/whop_intro_final.mp4" />
            <Navbar />
            {children}
          </LoaderProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
