import type { Metadata } from "next";
import { Geist, Geist_Mono, EB_Garamond } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Brier, MonaSans } from "@/fonts/fonts";
import Navbar from "@/components/navbar/navbar";
import { LoaderProvider } from "@/components/loader/loaderContext";
import LoaderWrapper from "@/components/loader/loader";
import { SmoothScroll } from "@/components/layout/lenis/smoothScroll";
import { CursorDot } from "@/components/layout/cursor/cursorDot";
import { MagnifyProvider } from "@/components/layout/magnifier/magnify";
import { CursorProvider } from "@/components/layout/cursor/cursorContext";
import Footer from "@/components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const garamond = EB_Garamond({
  variable: "--font-garamond",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${MonaSans.variable} ${Brier.variable} ${garamond.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          <CursorProvider>
            <MagnifyProvider>
              <CursorDot />
              <SmoothScroll>
                <LoaderProvider>
                  <LoaderWrapper src="/loader/whop_intro_final.mp4" />
                  <Navbar />
                  {children}
                  <Footer />
                </LoaderProvider>
              </SmoothScroll>
            </MagnifyProvider>
          </CursorProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
